sudo: required
dist: trusty
language: python
python:
  - "2.7"
services:
  - docker
env:
  global:
    - PATH="/usr/bin:$PATH"

before_install:
    # Ansible doesn't play well with virtualenv
  - deactivate
  - sudo apt-get update -qq
  - sudo apt-get install -y -o Dpkg::Options::="--force-confnew" docker-engine

install:
  - sudo pip install docker-py
    # software-properties-common for ubuntu 14.04
    # python-software-properties for ubuntu 12.04
  - sudo apt-get install -y sshpass software-properties-common python-software-properties
  - sudo -E apt-add-repository -y ppa:ansible/ansible
  - sudo apt-get update -qq
  - sudo apt-get install -y ansible
  - sudo rm /usr/bin/python && sudo ln -s /usr/bin/python2.7 /usr/bin/python
  - ansible-galaxy install -r tests/requirements.yml -p tests/roles/

script:
  # Ensure any invocation of ansible-playbook (i.e. sudo) results in host_key_checking disabled
  - ansible-playbook -i tests/inventory tests/main.yml --syntax-check
  - sudo ansible-playbook -i tests/inventory tests/main.yml

after_script:
  # Cleanup
  - sudo docker stop $(docker ps -aq) && sudo docker rm $(docker ps -aq)

#notifications:
  # notify ansible galaxy of test results
 # webhooks: http://galaxy-qa.ansible.com/api/v1/notifications/
