---
- name: Install nginx package
  apt: name=nginx state=present

- name: Copy nginx configuration
  template: src=nginx_config.j2 dest=/etc/nginx/sites-enabled/default

- name: Restart nginx service
  service: name=nginx state=restarted