---
- name: Install parse-server with npm
  npm: name=parse-server global=yes

- name: Install pm2 with npm
  npm: name=pm2 global=yes

- name: Create parse user and home directory
  user: name=parse system=yes createhome=yes password={{parse_user_crypted_password}}

- name: install setfacl support to allow becoming an unprivileged User
  apt: name=acl

- name: Create cloud code directory
  file: path=/home/parse/cloud state=directory
  become: yes
  become_user: parse

- name: Copy example cloud code for testing
  copy: src=main.js dest=/home/parse/cloud/main.js 
  become: yes
  become_user: parse

- name: Copy pm2 ecosystem file
  template: src=ecosystem.json.j2 dest=/home/parse/ecosystem.json
  become: yes
  become_user: parse

- name: Run ecosystem script with pm2
  command: pm2 start /home/parse/ecosystem.json
  become: yes
  become_user: parse

- name: pm2 save the process list
  command: pm2 save
  become: yes
  become_user: parse

- name: Check process list file
  stat: path=/home/parse/.pm2
  become: yes
  become_user: parse
  register: process_list_check

- name: Fail if process list file does not exist
  fail: msg="ERROR - Process list file /home/parse/.pm2 could not be created"
  when: not process_list_check.stat.exists

- name: pm2 install initialization scripts
  command: pm2 startup ubuntu -u parse --hp /home/parse/