---
- name: Check if certificate available
  stat: path=/etc/letsencrypt/live/{{parse_server_domain}}
  register: cert_check

- block:

  - name: Install Let's Encrypt and Dependencies
    apt: name={{item}} state=present force=yes
    with_items:
      - git
      - bc

  - name: Clone the letsencrypt repository from GitHub to /opt/letsencrypt
    git: repo=https://github.com/letsencrypt/letsencrypt dest=/opt/letsencrypt version=v0.8.1

  - name: Retrieve initial certificate
    shell: >
      /opt/letsencrypt/letsencrypt-auto certonly --standalone --agree-tos --renew-by-default --redirect --text 
      --email {{parse_server_email_for_certificate}} -d {{parse_server_domain}}
      {{'--server https://acme-staging.api.letsencrypt.org/directory' if parse_server_use_letsencrypt_staging else ''}}

  - name: Copy renew certs script
    template: src=renew_cert.sh.j2 dest=/home/parse/renew_certs.sh mode=555

  - name: Set Up Let's Encrypt Auto Renewal
    cron: name="renew certs" minute="1" hour="3" day="1" job="/home/parse/renew_certs.sh >> /var/log/le-renew.log"


  when: not cert_check.stat.exists