---
- name: Check if certificate available
  stat: path=/etc/letsencrypt/archive/{{parse_server_domain}}
  register: cert_check

- block:

  - name: Install Let's Encrypt and Dependencies
    apt: name={{item}} state=present force=yes
    with_items:
      - git
      - bc

  - name: Clone the letsencrypt repository from GitHub to /opt/letsencrypt
    git: repo=https://github.com/letsencrypt/letsencrypt dest=/opt/letsencrypt version=v0.8.1

  - name: Retrieve initial certificate
    shell: >
      /opt/letsencrypt/letsencrypt-auto certonly --standalone --agree-tos --renew-by-default --redirect --text 
      --email {{parse_server_email_for_certificate}} -d {{parse_server_domain}}
      {{'--server https://acme-staging.api.letsencrypt.org/directory' if parse_server_use_letsencrypt_staging else ''}} 

  - name: Set Up Let's Encrypt Auto Renewal
    cron: name="renew cert" minute="30" hour="2" weekday="1" job="/opt/letsencrypt/letsencrypt-auto renew >> /var/log/le-renew.log"

  - name: Set Up Let's Encrypt Auto Renewal
    cron: name="renew cert" minute="35" hour="2" weekday="1" job="cat /etc/letsencrypt/archive/{{parse_server_domain}}/{fullchain1.pem,privkey1.pem} > /etc/ssl/mongo.pem && chown mongodb:mongodb /etc/ssl/mongo.pem && chmod 600 /etc/ssl/mongo.pem"

  - name: Set Up nginx reload
    cron: name="reload nginx" minute="40" hour="2" weekday="1" job="/etc/init.d/nginx reload"

  when: not cert_check.stat.exists